#!/usr/bin/env python3
"""Build a single self-contained `grafana-cli` executable with PyInstaller.

Produces one file — no Python needed on the target. A frozen binary is
platform-specific, so run this once per OS/arch you want to ship;
`.github/workflows/release.yml` does linux/macOS/Windows on every tag.

    python scripts/build_binary.py                        # -> dist/grafana-cli
    python scripts/build_binary.py --output grafana-cli-linux-x86_64

This is Python rather than a shell script for one reason: **release.yml must not
own a second copy of the flag list.** The sibling OpenProject CLI ships
`build_binary.sh` *and* an inline PowerShell block in its release workflow that
re-states the same PyInstaller flags for Windows — two lists, one truth, and
nothing to stop them drifting apart until a released Windows binary silently
can't read the keyring. One cross-platform script, called identically by every
job, cannot drift.
"""

from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: PyInstaller freezes a *script*, not a package. This thin launcher does the
#: absolute import a top-level script needs. It is generated into the work dir
#: rather than committed: it is a build artifact, and a committed one would be a
#: second place for the entry point to be wrong.
#: ASCII-only, deliberately. This string is written out as a .py file and parsed
#: by a fresh interpreter, so one non-ASCII character kills the Windows build: an
#: em-dash in this docstring produced
#:   SyntaxError: invalid or missing encoding declaration
#: because Path.write_text() defaults to the LOCALE encoding on Windows (cp1252)
#: while Python reads .py as UTF-8. The explicit encoding= at the call site is the
#: real fix; keeping this ASCII is the belt to its braces.
LAUNCHER = '''\
"""Generated by scripts/build_binary.py - do not edit, do not commit."""

from grafanacli.cli import main

if __name__ == "__main__":
    main()
'''


def platform_extras(system: str) -> list[str]:
    """Per-OS keyring backend flags.

    keyring finds its OS backends through entry points / package metadata, which
    a frozen app drops by default. Without these the binary starts fine and then
    cannot read the token you stored — a failure that only shows up in the
    shipped artifact, never in a dev checkout.
    """
    if system == "Linux":
        return [
            "--collect-all", "secretstorage",
            "--collect-submodules", "jeepney",
            "--hidden-import", "keyring.backends.SecretService",
        ]
    if system == "Darwin":
        return ["--hidden-import", "keyring.backends.macOS"]
    if system == "Windows":
        return ["--hidden-import", "keyring.backends.Windows"]
    return []


def pyinstaller_args(
    name: str,
    *,
    system: str,
    launcher: str,
    distpath: str = "dist",
    workpath: str = "build/pyinstaller",
    specpath: str = "build",
) -> list[str]:
    """The full PyInstaller argv. Pure — the tests pin it."""
    return [
        "--noconfirm", "--clean", "--onefile",
        "--name", name,
        "--paths", "src",
        # keyring's backends again: --collect-all pulls the package's metadata and
        # data files, which is what makes backend discovery work at all.
        "--collect-all", "keyring",
        "--hidden-import", "keyring.backends.chainer",
        "--hidden-import", "keyring.backends.fail",
        *platform_extras(system),
        "--distpath", distpath,
        "--workpath", workpath,
        "--specpath", specpath,
        launcher,
    ]


def build_name(output: str, system: str) -> str:
    """The `--name` to hand PyInstaller, given the file we want out.

    PyInstaller appends `.exe` itself on Windows, so a requested
    `grafana-cli-windows-x86_64.exe` must go in without the suffix or we'd risk
    `…​.exe.exe`. We rename to the exact requested name afterwards regardless
    (see `main`), so this only has to avoid the double-suffix.
    """
    if system == "Windows" and output.lower().endswith(".exe"):
        return output[: -len(".exe")]
    return output


def find_built(distdir: Path, name: str) -> Path | None:
    """Locate what PyInstaller actually produced, suffix or not."""
    for candidate in (distdir / name, distdir / f"{name}.exe"):
        if candidate.exists():
            return candidate
    return None


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    """`--output NAME` is a contract with release.yml — it calls this script that
    way for every platform asset. Renaming the flag silently kills every release
    binary, so the parser is its own seam and the tests pin it."""
    parser = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    parser.add_argument(
        "--output", default="grafana-cli",
        help="Name of the produced file in dist/ (default: grafana-cli). "
             "Release CI passes the per-platform asset name, e.g. grafana-cli-linux-x86_64.",
    )
    parser.add_argument("--distpath", default="dist", help="Where to put the binary.")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)

    system = platform.system()
    workpath = ROOT / "build" / "pyinstaller"
    workpath.mkdir(parents=True, exist_ok=True)
    launcher = workpath / "graf_launcher.py"
    # encoding= is REQUIRED, not tidiness: without it Windows writes cp1252 and
    # PyInstaller's parse of this file fails with "invalid or missing encoding
    # declaration". Every write of a .py file needs this.
    launcher.write_text(LAUNCHER, encoding="utf-8")

    name = build_name(args.output, system)
    cmd = [sys.executable, "-m", "PyInstaller", *pyinstaller_args(
        name,
        system=system,
        launcher=str(launcher.relative_to(ROOT)),
        distpath=args.distpath,
        workpath=str(workpath.relative_to(ROOT)),
        specpath="build",
    )]
    print("$ " + " ".join(cmd))
    proc = subprocess.run(cmd, cwd=ROOT)
    if proc.returncode != 0:
        return proc.returncode

    distdir = ROOT / args.distpath
    built = find_built(distdir, name)
    if built is None:
        print(f"error: PyInstaller reported success but produced no file in {distdir}",
              file=sys.stderr)
        return 1

    # Hand back EXACTLY the filename that was asked for. release.yml smoke-tests
    # `./dist/<asset>` and then uploads that same path; a binary that is right but
    # named `foo` when the caller said `foo.exe` fails the job for no good reason.
    wanted = distdir / args.output
    if built != wanted:
        shutil.move(str(built), str(wanted))

    size_mb = wanted.stat().st_size / (1024 * 1024)
    print(f"\nBuilt: {wanted} ({size_mb:.1f} MB)")
    print(f"Try:   {wanted} --help")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
